### PR TITLE
Kill two custom pages; move their content to existing related pages

### PR DESCRIPTION
**Pull request by aklapper**
https://phabricator.wikimedia.org/T118522

### CODE REVIEW

**Comment by sanacl** [comment]
I'm testing it tomorrow morning

**Comment by sanacl** [comment]
scr-contributors.html needs at the bottom:

```
diff --git a/browser/scr-contributors.html b/browser/scr-contributors.html
index 7f461ff..55eb2a1 100644
--- a/browser/scr-contributors.html
+++ b/browser/scr-contributors.html
@@ -127,6 +127,11 @@
     <script src="./lib/timezones.js"></script>
     <script src="./lib/filter_panel.js"></script>
     <script src="./lib/events.js"></script>
+    <script type="text/javascript" src="js/mediawiki.js"></script>
+    <script type="text/javascript">
+            twitter_typeahead = true;
+        </script>
+   <script type="text/javascript" src="js/typeahead.jquery.js"></script>
   </body>
 </html>
```

**Comment by sanacl** [comment]
Same for scr-organizations.html

**Comment by aklapper** [comment]
Thanks for catching that. :( 
Grmpf. I fixed that in https://github.com/aklapper/mediawiki-dashboard/commit/99fc29667947c116d74a2dbf7e0de612b827c998 but probably should not have rebased seeing all the noise above. Sigh. GitHub and me aren't the best friends.

**Comment by sanacl** [comment]
About the "noise", let's be pragmatic, this product is frozen and the sooner the merge, the better.

It works.

**Pull request merged**
